name: Lint
on: [ pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@505e6394dae86d6a5c7fbb6e3fb8938e3e863830 # v3.1.1
      - name: Install dependencies
        run: |
          conda install -c conda-forge shellcheck
      - name: Shellcheck
        run: |
          echo "::add-matcher::.github/shellcheck-matcher.json"
          shellcheck --format=gcc $(find . -iname "*.sh")
          echo "::remove-matcher owner=shellcheck::"
